platform :ios, '7.0'

target 'Hackerspace' do

  pod 'AFNetworking', '~> 2.6'
  pod 'SDWebImage', '~>3.7'
  pod 'YYKit'
  pod 'Masonry'
  pod 'LCTabBarController'
  pod 'NJKWebViewProgress'
  pod 'HHAlertView', '~> 0.1.0'
  pod 'MBProgressHUD', '~> 0.9.2'
  pod 'BmobSDK'
end
